[tool.black]
skip-string-normalization = true

[tool.pytest.ini_options]
testpaths = [
    "{{ cookiecutter.python_package_name }}/tests"
]

[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"
